version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
      - image: cimg/mariadb:10.3.34
        environment:
          MYSQL_DATABASE: larasns
          MYSQL_USER: default
          MYSQL_PASSWORD: secret
    environment:
      APP_ENV: testing
      DB_CONNECTION: mysql
      DB_HOST: localhost
      DB_PORT: 3306
      DB_DATABASE: larasns
      DB_USERNAME: default
      DB_PASSWORD: secret
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run circleci-dev
      - run:
          name: get ready for mariadb
          command: |
            sudo docker-php-ext-install pdo_mysql
            dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: php test
          command: vendor/bin/phpunit 